//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SRRH.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SRRH.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!-- ####### HEY, I AM THE SOURCE EDITOR! #########--&gt;
        ///&lt;h2 style=&quot;text-align: center;&quot;&gt;S.R.R.H&lt;/h2&gt;
        ///&lt;h4 style=&quot;text-align: center;&quot;&gt;&lt;strong&gt;Sistema de Registro de Reservacion de Hoteleria&amp;nbsp;&lt;/strong&gt;&lt;/h4&gt;
        ///&lt;hr /&gt;
        ///&lt;h4 style=&quot;text-align: center;&quot;&gt;&amp;nbsp;&lt;/h4&gt;
        ///&lt;p&gt;&amp;nbsp;&lt;/p&gt;.
        /// </summary>
        internal static string cabecera {
            get {
                return ResourceManager.GetString("cabecera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Cantidad_de_clientes_en_un_año {
            get {
                object obj = ResourceManager.GetObject("Cantidad_de_clientes_en_un_año", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap logo_transparent {
            get {
                object obj = ResourceManager.GetObject("logo_transparent", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h4 style=&quot;text-align: center;&quot;&gt;&amp;nbsp;&lt;/h4&gt;
        ///&lt;hr /&gt;
        ///&lt;p style=&quot;text-align: right;&quot;&gt;&lt;strong&gt;Pag 1 de 1&lt;/strong&gt;&lt;/p&gt;
        ///&lt;p style=&quot;text-align: center;&quot;&gt;&lt;strong&gt;FECHA DE REPORTE: @DSFGFACHE&lt;/strong&gt;&lt;/p&gt;.
        /// </summary>
        internal static string pie {
            get {
                return ResourceManager.GetString("pie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h2 style=&quot;text-align: center;&quot;&gt;S.R.R.H&lt;/h2&gt;
        ///&lt;h4 style=&quot;text-align: center;&quot;&gt;&lt;strong&gt;Sistema de Registro de Reservacion de Hoteleria&amp;nbsp;&lt;/strong&gt;&lt;/h4&gt;
        ///&lt;hr /&gt;
        ///&lt;table style=&quot;height: 87px; width: 100%; border-collapse: collapse;&quot; border=&quot;0&quot;&gt;
        ///    &lt;tbody&gt;
        ///        &lt;tr style=&quot;height: 15px;&quot;&gt;
        ///            &lt;td style=&quot;width: 25%; height: 15px;&quot;&gt;Cliente&lt;/td&gt;
        ///            &lt;td style=&quot;width: 25%; height: 15px; text-align: right;&quot;&gt; @CLIEIT &lt;/td&gt;
        ///        &lt;/tr&gt;
        ///        &lt;tr style=&quot;height: 18px;&quot;&gt;
        ///            &lt;td st [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string plantilla_comprobate {
            get {
                return ResourceManager.GetString("plantilla_comprobate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!-- ####### HEY, I AM THE SOURCE EDITOR! #########--&gt;
        ///&lt;h2 style=&quot;text-align: center;&quot;&gt;S.R.R.H&lt;/h2&gt;
        ///&lt;h4 style=&quot;text-align: center;&quot;&gt;&lt;strong&gt;Sistema de Registro de Reservacion de Hoteleria&amp;nbsp;&lt;/strong&gt;&lt;/h4&gt;
        ///&lt;hr /&gt;
        ///&lt;table style=&quot;height: 87px; width: 100%; border-collapse: collapse;&quot; border=&quot;0&quot;&gt;
        ///&lt;tbody&gt;
        ///&lt;tr style=&quot;height: 15px;&quot;&gt;
        ///&lt;td style=&quot;width: 25%; height: 15px;&quot;&gt;Cliente&lt;/td&gt;
        ///&lt;td id=&quot;Cliente_ID&quot; style=&quot;width: 25%; height: 15px; text-align: right;&quot;&gt;@CLIENTE&lt;/td&gt;
        ///&lt;/tr&gt;
        ///&lt;tr style=&quot;height: 18px;&quot;&gt;        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string plantilla_ticket {
            get {
                return ResourceManager.GetString("plantilla_ticket", resourceCulture);
            }
        }
    }
}
